name: deploy to lambda
on:
  push:
    branches:
      - 'main'
    paths:
      - 'lambda/lambda_function.py'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Install AWS CLI
        run: |
          sudo apt install aws-cli
          sudo apt-get install zip unzip
      - name: Zip lambda_function code
        run: |
          zip lambda_function.zip ./lambda/lambda_function.py
      - name: Deploy to lambda
        run: |
          aws lambda update-function-code --function-name lambda-action-test --zip-file lambda_function.zip
